<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
		<TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
		<RootNamespace>BlueSapphire</RootNamespace>
		<ApplicationManifest>app.manifest</ApplicationManifest>
		<Platforms>x64</Platforms>
		<PlatformTarget>x64</PlatformTarget>
		<RuntimeIdentifiers>win-x64</RuntimeIdentifiers>

		<PublishAot>false</PublishAot>
		<PublishReadyToRun>true</PublishReadyToRun>
		<OptimizationPreference>Speed</OptimizationPreference>

		<WindowsAppSDKSelfContained>true</WindowsAppSDKSelfContained>
		<SelfContained>true</SelfContained>
		<UseWinUI>true</UseWinUI>
		<EnableMsixTooling>true</EnableMsixTooling>
		<Nullable>enable</Nullable>
		<LangVersion>preview</LangVersion>
		<EnableNETAnalyzers>true</EnableNETAnalyzers>
		<AnalysisLevel>latest</AnalysisLevel>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<WindowsPackageType>None</WindowsPackageType>
		<ApplicationIcon>BS.ico</ApplicationIcon>
		<Version>1.0.3</Version>
		<AssemblyVersion>1.0.3.0</AssemblyVersion>
		<FileVersion>1.0.3.0</FileVersion>
		<InformationalVersion>1.0.3</InformationalVersion>

		<EnableDefaultPageItems>true</EnableDefaultPageItems>
		<EnableDefaultCompileItems>true</EnableDefaultCompileItems>
	    <NoWarn>$(NoWarn);CA1416</NoWarn>
	</PropertyGroup>

	<ItemGroup>
		<Content Include="Assets\**" />
		<Content Update="Assets\CleanerRules.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
			<CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
		</Content>
		<None Remove="DevLogInputDialog.xaml" />
		<None Remove="Views\DevLogPage.xaml" />
		<Content Include="BS.ico">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
			<CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
		</Content>
		<Manifest Include="$(ApplicationManifest)" />
	</ItemGroup>

	<ItemGroup>
		<Compile Remove="BlueSapphire.Tests\**\*.cs" />
		<EmbeddedResource Remove="BlueSapphire.Tests\**\*" />
		<None Remove="BlueSapphire.Tests\**\*" />
		<Page Remove="BlueSapphire.Tests\**\*" />
	</ItemGroup>

	<ItemGroup>
		<Content Include="Assets\DevMatrixLog.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
			<CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
		</Content>
	</ItemGroup>
	
	<ItemGroup>
		<PackageReference Include="Markdig" Version="1.3.1" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.3" />
		<PackageReference Include="Microsoft.Extensions.Http" Version="10.0.3" />
		<PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.3" />
		<PackageReference Include="System.Security.Cryptography.ProtectedData" Version="8.0.0" />
		<PackageReference Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.26100.7705" />
		<PackageReference Include="Microsoft.WindowsAppSDK" Version="1.8.260209005" />
		<PackageReference Include="Microsoft.Graphics.Win2D" Version="1.3.2" />
		<PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
	</ItemGroup>

	<ItemGroup>
		<Compile Update="Properties\Resources.Designer.cs">
			<DesignTime>True</DesignTime>
			<AutoGen>True</AutoGen>
			<DependentUpon>Resources.resx</DependentUpon>
		</Compile>
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Update="Properties\Resources.resx">
			<Generator>ResXFileCodeGenerator</Generator>
			<LastGenOutput>Resources.Designer.cs</LastGenOutput>
		</EmbeddedResource>
	</ItemGroup>

	<ItemGroup>
	  <Page Update="DevLogInputDialog.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </Page>
	  <Page Update="Views\DevLogPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </Page>
	</ItemGroup>
</Project>


