<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
		<TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
		<RootNamespace>BlueSapphire</RootNamespace>
		<ApplicationManifest>app.manifest</ApplicationManifest>
		<Platforms>x64</Platforms>
		<PlatformTarget>x64</PlatformTarget>
		<RuntimeIdentifiers>win-x64</RuntimeIdentifiers>

		<PublishAot>false</PublishAot>
		<PublishReadyToRun>true</PublishReadyToRun>
		<OptimizationPreference>Speed</OptimizationPreference>

		<WindowsAppSDKSelfContained>true</WindowsAppSDKSelfContained>
		<SelfContained>true</SelfContained>
		<UseWinUI>true</UseWinUI>
		<EnableMsixTooling>true</EnableMsixTooling>
		<Nullable>enable</Nullable>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<WindowsPackageType>None</WindowsPackageType>
		<ApplicationIcon>BS.ico</ApplicationIcon>

		<EnableDefaultPageItems>true</EnableDefaultPageItems>
		<EnableDefaultCompileItems>true</EnableDefaultCompileItems>
	</PropertyGroup>

	<ItemGroup>
		<Content Include="Assets\**" />
		<Content Include="BS.ico" />
		<Manifest Include="$(ApplicationManifest)" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.3" />
		<PackageReference Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.26100.7705" />
		<PackageReference Include="Microsoft.WindowsAppSDK" Version="1.8.260209005" />
		<PackageReference Include="Microsoft.Graphics.Win2D" Version="1.3.2" />
		<PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
	</ItemGroup>

	<ItemGroup>
		<Compile Update="Properties\Resources.Designer.cs">
			<DesignTime>True</DesignTime>
			<AutoGen>True</AutoGen>
			<DependentUpon>Resources.resx</DependentUpon>
		</Compile>
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Update="Properties\Resources.resx">
			<Generator>ResXFileCodeGenerator</Generator>
			<LastGenOutput>Resources.Designer.cs</LastGenOutput>
		</EmbeddedResource>
	</ItemGroup>
</Project>